using System;
using System.Collections.Generic;
using System.Text;

namespace Contracts
{
	public class Consts
	{
		public const string
			CONTEXT_ITEM_KEY_CREATOR = "CREATOR",
			CONTEXT_ITEM_KEY_THEME_MODULE_NAME = "THEMEMODULE",
			CONTEXT_ITEM_KEY_THEME_LAYOUT_PATH = "THEMELAYOUTPATH",
			CONTEXT_ITEM_KEY_ADMIN_THEME_LAYOUT_PATH = "ADMINTHEMELAYOUTPATH",
			CONTEXT_ITEM_IS_IN_DEBUG = "DEBUGMODE",
			CONTEXT_ITEM_KEY_AUTH = "AUTHENTICATOR",
			MODULES_BASE_PATH = "__";
	}
}
